language: java

jdk:
  - oraclejdk8


addons:
  sonarcloud:
    organization: " aurorasic-github" # the key of the org you chose at step #3
    token:
      secure: 7a2e339ba7c2e8ecde350714862d53529b496ab0 # encrypted value of your token


#install:
 # - mvn clean package --batch-mode -V -DskipTests=true -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
script: mvn package -DskipTests=true -Dmaven.test.skip=true -Dmaven.javadoc.skip=true

after_success:
  - mvn jacoco:report  sonar:sonar
  
