language: java
branches:
  only:
    - master
    - /^release.*$/
    - /^dev.*$/

jdk:
  - oraclejdk8

cache:
  directories:
    - .autoconf
    - $HOME/.m2
addons:
  sonarcloud:
    organization: "aurorasic-github"

script: mvn package -DskipTests=true -Dmaven.test.skip=true -Dmaven.javadoc.skip=true

after_success:
  - mvn deploy --settings bin/setting -DskipTests=true -Dmaven.javadoc.skip=true
  - mvn jacoco:report  sonar:sonar
  
