language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - .autoconf
    - $HOME/.m2
addons:
  sonarcloud:
    organization: "aurorasic-github"

script: mvn package -DskipTests=true -Dmaven.javadoc.skip=true

after_success:
  - mvn -s `pwd`/bin/setting.xml deploy -DskipTests=true -Dmaven.javadoc.skip=true
  - mvn jacoco:report  sonar:sonar
  
