language: java

branches:
  only:
    - master
    - /^release(-|_).*$/
    - /^dev(-|_).*$/
    - /^v(\d+.){1,2}\d+.*$/
    - /^feature(-|_).*$/
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar
addons:
  sonarcloud:
    organization: "aurorasic-github"

script: mvn package -DskipTests=true -Dmaven.javadoc.skip=true

after_success:
  - bin/deploy-snapshot.sh
  - mvn jacoco:report  sonar:sonar
