language: java
branches:
  only:
    - master
    - /^release.*$/
    - /^dev.*$/
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar
addons:
  sonarcloud:
    organization: "aurorasic-github"

script: mvn package -DskipTests=true -Dmaven.javadoc.skip=true

after_success:
  - mvn -s .bin/setting.xml deploy -DskipTests -Dmaven.javadoc.skip=true
  - mvn jacoco:report  sonar:sonar
