sofajraft:
  serverIdStr: 127.0.0.1:9002
  initConfStr: 127.0.0.1:9000,127.0.0.1:9001,127.0.0.1:9002
  dataPath: /tmp/sofajraft/data2
  port: 10002
logging:
  path: /tmp/sofajraft/log2
management:
  shell:
    ssh:
      port: 2002
  port: 6062
server:
  port: 7072